language: go
go:
  - "1.10.x"
script:
  - set -e
  - go get -v ./...
  - diff -u <(echo -n) <(gofmt -d ./)
  - go vet .
  - go test -cover -race ./...
  - export GITHASH=$(git rev-parse HEAD) # Git commit hash is used as version string in main.go
  - go build -ldflags "-extldflags '-static' -X main.githash=$GITHASH"
