language: go
go:
  - "1.11.x"
install:
  - /bin/true
script:
  - set -e
  - diff -u <(echo -n) <(gofmt -d ./)
  - go vet .
  - go test -cover -race ./...
  - export GITHASH=$(git rev-parse HEAD) # Git commit hash is used as version string in main.go
  - go build -v -ldflags "-extldflags '-static' -X main.githash=$GITHASH"
