apiVersion: batch/v1
kind: Job
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - name: count1
        image: ubuntu
        command: ["sh", "-c", "for i in `seq 1 10`; do echo $i; sleep 1; done; false"]
      restartPolicy: Never
      backoffLimit: 0